### ISSUE TITLE
did you retire this project?

### ISSUE THREAD

**Issue by robbiemu** [albertovecina/SeekBarIndicated#4]
the readme says v. 1.1.0 but the source says it is at 1.2.1 — but if I import 1.2.1 I get some new methods (setMax/setMin) but not others (setValue) ..

**Comment by albertovecina** [comment]
I will check it. Thanks.

**Comment by albertovecina** [comment]
v1.2.3 is available from 29/10/2015 - https://bintray.com/albertovecina/maven/SeekBarIndicated/1.2.3/view
